#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
# Source0 file verified with key 0x3672782A9BF368F3 (d@drobilla.net)
#
Name     : lv2
Version  : 1.18.10
Release  : 9
URL      : https://lv2plug.in/spec/lv2-1.18.10.tar.xz
Source0  : https://lv2plug.in/spec/lv2-1.18.10.tar.xz
Source1  : https://lv2plug.in/spec/lv2-1.18.10.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: lv2-bin = %{version}-%{release}
Requires: lv2-lib = %{version}-%{release}
Requires: lv2-license = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : gtk+-dev
BuildRequires : libsamplerate-dev
BuildRequires : libsndfile-dev
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(sndfile)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!-- SPDX-License-Identifier: ISC -->
LV2
===
LV2 is a plugin standard for audio systems.  It defines an extensible C API for
plugins, and a format for self-contained "bundle" directories that contain
plugins, metadata, and other resources.  See <http://lv2plug.in/> for more
information.

%package bin
Summary: bin components for the lv2 package.
Group: Binaries
Requires: lv2-license = %{version}-%{release}

%description bin
bin components for the lv2 package.


%package dev
Summary: dev components for the lv2 package.
Group: Development
Requires: lv2-lib = %{version}-%{release}
Requires: lv2-bin = %{version}-%{release}
Provides: lv2-devel = %{version}-%{release}
Requires: lv2 = %{version}-%{release}

%description dev
dev components for the lv2 package.


%package doc
Summary: doc components for the lv2 package.
Group: Documentation

%description doc
doc components for the lv2 package.


%package lib
Summary: lib components for the lv2 package.
Group: Libraries
Requires: lv2-license = %{version}-%{release}

%description lib
lib components for the lv2 package.


%package license
Summary: license components for the lv2 package.
Group: Default

%description license
license components for the lv2 package.


%prep
%setup -q -n lv2-1.18.10
cd %{_builddir}/lv2-1.18.10
pushd ..
cp -a lv2-1.18.10 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1696518747
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/lv2
cp %{_builddir}/lv2-%{version}/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/lv2/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/lv2-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/lv2/6bc5bdae464255ca81b3f581488ceb76d436c35e || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/lv2/atom.lv2/atom.meta.ttl
/usr/lib64/lv2/atom.lv2/atom.ttl
/usr/lib64/lv2/atom.lv2/manifest.ttl
/usr/lib64/lv2/buf-size.lv2/buf-size.meta.ttl
/usr/lib64/lv2/buf-size.lv2/buf-size.ttl
/usr/lib64/lv2/buf-size.lv2/manifest.ttl
/usr/lib64/lv2/core.lv2/lv2core.meta.ttl
/usr/lib64/lv2/core.lv2/lv2core.ttl
/usr/lib64/lv2/core.lv2/manifest.ttl
/usr/lib64/lv2/core.lv2/meta.ttl
/usr/lib64/lv2/core.lv2/people.ttl
/usr/lib64/lv2/data-access.lv2/data-access.meta.ttl
/usr/lib64/lv2/data-access.lv2/data-access.ttl
/usr/lib64/lv2/data-access.lv2/manifest.ttl
/usr/lib64/lv2/dynmanifest.lv2/dynmanifest.meta.ttl
/usr/lib64/lv2/dynmanifest.lv2/dynmanifest.ttl
/usr/lib64/lv2/dynmanifest.lv2/manifest.ttl
/usr/lib64/lv2/eg-amp.lv2/amp.ttl
/usr/lib64/lv2/eg-amp.lv2/manifest.ttl
/usr/lib64/lv2/eg-fifths.lv2/fifths.ttl
/usr/lib64/lv2/eg-fifths.lv2/manifest.ttl
/usr/lib64/lv2/eg-metro.lv2/manifest.ttl
/usr/lib64/lv2/eg-metro.lv2/metro.ttl
/usr/lib64/lv2/eg-midigate.lv2/manifest.ttl
/usr/lib64/lv2/eg-midigate.lv2/midigate.ttl
/usr/lib64/lv2/eg-params.lv2/manifest.ttl
/usr/lib64/lv2/eg-params.lv2/params.ttl
/usr/lib64/lv2/eg-sampler.lv2/click.wav
/usr/lib64/lv2/eg-sampler.lv2/manifest.ttl
/usr/lib64/lv2/eg-sampler.lv2/sampler.ttl
/usr/lib64/lv2/eg-scope.lv2/examploscope.ttl
/usr/lib64/lv2/eg-scope.lv2/manifest.ttl
/usr/lib64/lv2/event.lv2/event.meta.ttl
/usr/lib64/lv2/event.lv2/event.ttl
/usr/lib64/lv2/event.lv2/manifest.ttl
/usr/lib64/lv2/instance-access.lv2/instance-access.meta.ttl
/usr/lib64/lv2/instance-access.lv2/instance-access.ttl
/usr/lib64/lv2/instance-access.lv2/manifest.ttl
/usr/lib64/lv2/log.lv2/log.meta.ttl
/usr/lib64/lv2/log.lv2/log.ttl
/usr/lib64/lv2/log.lv2/manifest.ttl
/usr/lib64/lv2/midi.lv2/manifest.ttl
/usr/lib64/lv2/midi.lv2/midi.meta.ttl
/usr/lib64/lv2/midi.lv2/midi.ttl
/usr/lib64/lv2/morph.lv2/manifest.ttl
/usr/lib64/lv2/morph.lv2/morph.meta.ttl
/usr/lib64/lv2/morph.lv2/morph.ttl
/usr/lib64/lv2/options.lv2/manifest.ttl
/usr/lib64/lv2/options.lv2/options.meta.ttl
/usr/lib64/lv2/options.lv2/options.ttl
/usr/lib64/lv2/parameters.lv2/manifest.ttl
/usr/lib64/lv2/parameters.lv2/parameters.meta.ttl
/usr/lib64/lv2/parameters.lv2/parameters.ttl
/usr/lib64/lv2/patch.lv2/manifest.ttl
/usr/lib64/lv2/patch.lv2/patch.meta.ttl
/usr/lib64/lv2/patch.lv2/patch.ttl
/usr/lib64/lv2/port-groups.lv2/manifest.ttl
/usr/lib64/lv2/port-groups.lv2/port-groups.meta.ttl
/usr/lib64/lv2/port-groups.lv2/port-groups.ttl
/usr/lib64/lv2/port-props.lv2/manifest.ttl
/usr/lib64/lv2/port-props.lv2/port-props.meta.ttl
/usr/lib64/lv2/port-props.lv2/port-props.ttl
/usr/lib64/lv2/presets.lv2/manifest.ttl
/usr/lib64/lv2/presets.lv2/presets.meta.ttl
/usr/lib64/lv2/presets.lv2/presets.ttl
/usr/lib64/lv2/resize-port.lv2/manifest.ttl
/usr/lib64/lv2/resize-port.lv2/resize-port.meta.ttl
/usr/lib64/lv2/resize-port.lv2/resize-port.ttl
/usr/lib64/lv2/schemas.lv2/dcterms.ttl
/usr/lib64/lv2/schemas.lv2/doap.ttl
/usr/lib64/lv2/schemas.lv2/foaf.ttl
/usr/lib64/lv2/schemas.lv2/manifest.ttl
/usr/lib64/lv2/schemas.lv2/owl.ttl
/usr/lib64/lv2/schemas.lv2/rdf.ttl
/usr/lib64/lv2/schemas.lv2/rdfs.ttl
/usr/lib64/lv2/schemas.lv2/xsd.ttl
/usr/lib64/lv2/state.lv2/manifest.ttl
/usr/lib64/lv2/state.lv2/state.meta.ttl
/usr/lib64/lv2/state.lv2/state.ttl
/usr/lib64/lv2/time.lv2/manifest.ttl
/usr/lib64/lv2/time.lv2/time.meta.ttl
/usr/lib64/lv2/time.lv2/time.ttl
/usr/lib64/lv2/ui.lv2/manifest.ttl
/usr/lib64/lv2/ui.lv2/ui.meta.ttl
/usr/lib64/lv2/ui.lv2/ui.ttl
/usr/lib64/lv2/units.lv2/manifest.ttl
/usr/lib64/lv2/units.lv2/units.meta.ttl
/usr/lib64/lv2/units.lv2/units.ttl
/usr/lib64/lv2/uri-map.lv2/manifest.ttl
/usr/lib64/lv2/uri-map.lv2/uri-map.meta.ttl
/usr/lib64/lv2/uri-map.lv2/uri-map.ttl
/usr/lib64/lv2/urid.lv2/manifest.ttl
/usr/lib64/lv2/urid.lv2/urid.meta.ttl
/usr/lib64/lv2/urid.lv2/urid.ttl
/usr/lib64/lv2/worker.lv2/manifest.ttl
/usr/lib64/lv2/worker.lv2/worker.meta.ttl
/usr/lib64/lv2/worker.lv2/worker.ttl

%files bin
%defattr(-,root,root,-)
/usr/bin/lv2_validate

%files dev
%defattr(-,root,root,-)
/usr/include/lv2.h
/usr/include/lv2/atom/atom.h
/usr/include/lv2/atom/forge.h
/usr/include/lv2/atom/util.h
/usr/include/lv2/buf-size/buf-size.h
/usr/include/lv2/core/attributes.h
/usr/include/lv2/core/lv2.h
/usr/include/lv2/core/lv2_util.h
/usr/include/lv2/data-access/data-access.h
/usr/include/lv2/dynmanifest/dynmanifest.h
/usr/include/lv2/event/event-helpers.h
/usr/include/lv2/event/event.h
/usr/include/lv2/instance-access/instance-access.h
/usr/include/lv2/log/log.h
/usr/include/lv2/log/logger.h
/usr/include/lv2/lv2plug.in/ns/ext/atom/atom.h
/usr/include/lv2/lv2plug.in/ns/ext/atom/forge.h
/usr/include/lv2/lv2plug.in/ns/ext/atom/util.h
/usr/include/lv2/lv2plug.in/ns/ext/buf-size/buf-size.h
/usr/include/lv2/lv2plug.in/ns/ext/data-access/data-access.h
/usr/include/lv2/lv2plug.in/ns/ext/dynmanifest/dynmanifest.h
/usr/include/lv2/lv2plug.in/ns/ext/event/event-helpers.h
/usr/include/lv2/lv2plug.in/ns/ext/event/event.h
/usr/include/lv2/lv2plug.in/ns/ext/instance-access/instance-access.h
/usr/include/lv2/lv2plug.in/ns/ext/log/log.h
/usr/include/lv2/lv2plug.in/ns/ext/log/logger.h
/usr/include/lv2/lv2plug.in/ns/ext/midi/midi.h
/usr/include/lv2/lv2plug.in/ns/ext/morph/morph.h
/usr/include/lv2/lv2plug.in/ns/ext/options/options.h
/usr/include/lv2/lv2plug.in/ns/ext/parameters/parameters.h
/usr/include/lv2/lv2plug.in/ns/ext/patch/patch.h
/usr/include/lv2/lv2plug.in/ns/ext/port-groups/port-groups.h
/usr/include/lv2/lv2plug.in/ns/ext/port-props/port-props.h
/usr/include/lv2/lv2plug.in/ns/ext/presets/presets.h
/usr/include/lv2/lv2plug.in/ns/ext/resize-port/resize-port.h
/usr/include/lv2/lv2plug.in/ns/ext/state/state.h
/usr/include/lv2/lv2plug.in/ns/ext/time/time.h
/usr/include/lv2/lv2plug.in/ns/ext/uri-map/uri-map.h
/usr/include/lv2/lv2plug.in/ns/ext/urid/urid.h
/usr/include/lv2/lv2plug.in/ns/ext/worker/worker.h
/usr/include/lv2/lv2plug.in/ns/extensions/ui/ui.h
/usr/include/lv2/lv2plug.in/ns/extensions/units/units.h
/usr/include/lv2/lv2plug.in/ns/lv2core/attributes.h
/usr/include/lv2/lv2plug.in/ns/lv2core/lv2.h
/usr/include/lv2/lv2plug.in/ns/lv2core/lv2_util.h
/usr/include/lv2/midi/midi.h
/usr/include/lv2/morph/morph.h
/usr/include/lv2/options/options.h
/usr/include/lv2/parameters/parameters.h
/usr/include/lv2/patch/patch.h
/usr/include/lv2/port-groups/port-groups.h
/usr/include/lv2/port-props/port-props.h
/usr/include/lv2/presets/presets.h
/usr/include/lv2/resize-port/resize-port.h
/usr/include/lv2/state/state.h
/usr/include/lv2/time/time.h
/usr/include/lv2/ui/ui.h
/usr/include/lv2/units/units.h
/usr/include/lv2/uri-map/uri-map.h
/usr/include/lv2/urid/urid.h
/usr/include/lv2/worker/worker.h
/usr/lib64/pkgconfig/lv2.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/lv2/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/lv2/eg-amp.lv2/amp.so
/V3/usr/lib64/lv2/eg-fifths.lv2/fifths.so
/V3/usr/lib64/lv2/eg-metro.lv2/metro.so
/V3/usr/lib64/lv2/eg-midigate.lv2/midigate.so
/V3/usr/lib64/lv2/eg-params.lv2/params.so
/V3/usr/lib64/lv2/eg-sampler.lv2/sampler.so
/V3/usr/lib64/lv2/eg-sampler.lv2/sampler_ui.so
/V3/usr/lib64/lv2/eg-scope.lv2/examploscope.so
/V3/usr/lib64/lv2/eg-scope.lv2/examploscope_ui.so
/usr/lib64/lv2/eg-amp.lv2/amp.so
/usr/lib64/lv2/eg-fifths.lv2/fifths.so
/usr/lib64/lv2/eg-metro.lv2/metro.so
/usr/lib64/lv2/eg-midigate.lv2/midigate.so
/usr/lib64/lv2/eg-params.lv2/params.so
/usr/lib64/lv2/eg-sampler.lv2/sampler.so
/usr/lib64/lv2/eg-sampler.lv2/sampler_ui.so
/usr/lib64/lv2/eg-scope.lv2/examploscope.so
/usr/lib64/lv2/eg-scope.lv2/examploscope_ui.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lv2/6bc5bdae464255ca81b3f581488ceb76d436c35e
/usr/share/package-licenses/lv2/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
